### ISSUE TITLE
has_content? not implemented

### ISSUE THREAD

**Issue by kbaum** [DavyJonesLocker/capybara-email#26]
When i try to use has_content? like:

``` ruby
current_email.should have_content "1 view "
```

It comes back with:

```
 1) TrafficReportMailer traffic_report traffic goes up from 0 has the total views in the last week
     Failure/Error: current_email.should have_content "1 view "
     NotImplementedError:
       NotImplementedError
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/driver/node.rb:12:in `all_text'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/element.rb:59:in `block in text'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/base.rb:77:in `synchronize'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/element.rb:57:in `text'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/document.rb:21:in `text'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/matchers.rb:466:in `text_found?'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/matchers.rb:219:in `block in has_text?'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/base.rb:81:in `synchronize'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/node/matchers.rb:218:in `has_text?'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/capybara-2.1.0/lib/capybara/rspec/matchers.rb:46:in `matches?'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/rspec-expectations-2.12.1/lib/rspec/expectations/handler.rb:23:in `handle_matcher'
     # /Users/karl/.rvm/gems/ruby-2.0.0-p195@viewthespace/gems/rspec-expectations-2.12.1/lib/rspec/expectations/syntax.rb:53:in `should'
     # ./spec/mailers/traffic_report_mailer_spec.rb:93:in `block (4 levels) in <top (required)>
```

I was able to fix address the issue with this commit:

https://github.com/kbaum/capybara-email/commit/f454a52b9f1c3f8fb1f8df2b0aaed32f4e3a830b

But i wasn't able to reproduce the problem within the driver spec.  Any idea why i would only be able to reproduce within my own spec?

thx!

**Comment by getscripted** [comment]
I had this issue, and it disappeared after updating to edge gem version. Thanks!
